services:
  - type: web
    name: social-media-tool
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn -w 1 -k gthread --threads 8 --timeout 180 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 2
